[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.ormolu]
command = "ormolu"
includes = ["*.hs"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
         "*.json",
         "*.yaml",
         "*.md",
         "*.tsx?",
         "*.jsx?"
]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]
